changeLogFile: db/changelog/changelog.xml
url: mongodb://localhost:27017/usersdb
# Для MongoDB потрібен спеціальний розширювач, ми вкажемо шлях до нього пізніше
driver: liquibase.ext.mongodb.database.MongoClientDriver
