version: '3.8'
services:
  # 1. Сервіс де запускається Node.js
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_HOSTNAME: mongo 
      MONGO_DB_PORT: 27017
      MONGO_DB: usersdb
    depends_on:
      - mongo

  # 2. Сервіс MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: